In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tree.base import DecisionTree
from metrics import *
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

np.random.seed(42)
# Reading the data
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
data = pd.read_csv(url, delim_whitespace=True, header=None,
                 names=["mpg", "cylinders", "displacement", "horsepower", "weight",
                        "acceleration", "model year", "origin", "car name"])
# Clean the above data by removing redundant columns and rows with junk values --- IGNORE ---

/var/folders/6j/f2lgwpsj3s124b4pqjz_g_qm0000gn/T/ipykernel_12234/3427653393.py:12: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(url, delim_whitespace=True, header=None,

In [9]:
data

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [10]:
data = data[data['horsepower']!='?']
y = data['mpg']
X = data.drop(['mpg', 'car name'], axis=1)
display(X)
display(y)

,cylinders,displacement,horsepower,weight,acceleration,model year,origin
0,8,307.0,130.0,3504.0,12.0,70,1
1,8,350.0,165.0,3693.0,11.5,70,1
2,8,318.0,150.0,3436.0,11.0,70,1
3,8,304.0,150.0,3433.0,12.0,70,1
4,8,302.0,140.0,3449.0,10.5,70,1
...,...,...,...,...,...,...,...
393,4,140.0,86.00,2790.0,15.6,82,1
394,4,97.0,52.00,2130.0,24.6,82,2
395,4,135.0,84.00,2295.0,11.6,82,1
396,4,120.0,79.00,2625.0,18.6,82,1
397,4,119.0,82.00,2720.0,19.4,82,1

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 392, dtype: float64

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
tree = DecisionTree(criterion='information_gain', max_depth=5)
tree.fit(x_train, y_train)
y_pred = tree.predict(x_test)
print("Custom Decision Tree Regressor Performance:")
print("RMSE:", rmse(y_test, y_pred))
print("MAE:", mae(y_test, y_pred))

Custom Decision Tree Regressor Performance:
RMSE: 8.171591342460893
MAE: 6.7758636363636375

In [12]:
sklearn_tree = DecisionTreeRegressor(random_state=42)
sklearn_tree.fit(x_train, y_train)
y_pred_sklearn = sklearn_tree.predict(x_test)
print("Sklearn Decision Tree Regressor Performance:")
print("RMSE:", rmse(y_test, y_pred_sklearn))
print("MAE:", mae(y_test, y_pred_sklearn))

Sklearn Decision Tree Regressor Performance:
RMSE: 10.017121705995553
MAE: 7.736363636363635